# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(2249, 884)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.horizontalLayoutWidget_3 = QtGui.QWidget(self.centralWidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(20, 0, 2131, 841))
        self.horizontalLayoutWidget_3.setObjectName(_fromUtf8("horizontalLayoutWidget_3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_2.setMargin(11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalGroupBox = QtGui.QGroupBox(self.horizontalLayoutWidget_3)
        self.verticalGroupBox.setObjectName(_fromUtf8("verticalGroupBox"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalGroupBox)
        self.verticalLayout_2.setMargin(11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.verticalGroupBox_2 = QtGui.QGroupBox(self.verticalGroupBox)
        self.verticalGroupBox_2.setObjectName(_fromUtf8("verticalGroupBox_2"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.verticalGroupBox_2)
        self.verticalLayout_4.setMargin(11)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label = QtGui.QLabel(self.verticalGroupBox_2)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_4.addWidget(self.label)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setMargin(11)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.pushButtonDraftPlayer = QtGui.QPushButton(self.verticalGroupBox_2)
        self.pushButtonDraftPlayer.setEnabled(False)
        self.pushButtonDraftPlayer.setObjectName(_fromUtf8("pushButtonDraftPlayer"))
        self.horizontalLayout_3.addWidget(self.pushButtonDraftPlayer)
        self.pushButtonUndoDraftedPlayer = QtGui.QPushButton(self.verticalGroupBox_2)
        self.pushButtonUndoDraftedPlayer.setEnabled(False)
        self.pushButtonUndoDraftedPlayer.setObjectName(_fromUtf8("pushButtonUndoDraftedPlayer"))
        self.horizontalLayout_3.addWidget(self.pushButtonUndoDraftedPlayer)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.addWidget(self.verticalGroupBox_2)
        self.label_2 = QtGui.QLabel(self.verticalGroupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_2.addWidget(self.label_2)
        self.lineEditPlayerSearch = QtGui.QLineEdit(self.verticalGroupBox)
        self.lineEditPlayerSearch.setEnabled(False)
        self.lineEditPlayerSearch.setObjectName(_fromUtf8("lineEditPlayerSearch"))
        self.verticalLayout_2.addWidget(self.lineEditPlayerSearch)
        self.listWidgetPlayerList = QtGui.QListWidget(self.verticalGroupBox)
        self.listWidgetPlayerList.setEnabled(False)
        self.listWidgetPlayerList.setObjectName(_fromUtf8("listWidgetPlayerList"))
        item = QtGui.QListWidgetItem()
        self.listWidgetPlayerList.addItem(item)
        self.verticalLayout_2.addWidget(self.listWidgetPlayerList)
        self.horizontalLayout_2.addWidget(self.verticalGroupBox)
        self.verticalGroupBox_21 = QtGui.QGroupBox(self.horizontalLayoutWidget_3)
        self.verticalGroupBox_21.setObjectName(_fromUtf8("verticalGroupBox_21"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.verticalGroupBox_21)
        self.verticalLayout_6.setMargin(11)
        self.verticalLayout_6.setSpacing(6)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setMargin(11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 12, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 6, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 1, 2, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 1, 8, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 1, 4, 1, 1)
        self.lineEditStartMockDraft = QtGui.QLineEdit(self.verticalGroupBox_21)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditStartMockDraft.sizePolicy().hasHeightForWidth())
        self.lineEditStartMockDraft.setSizePolicy(sizePolicy)
        self.lineEditStartMockDraft.setObjectName(_fromUtf8("lineEditStartMockDraft"))
        self.gridLayout.addWidget(self.lineEditStartMockDraft, 1, 11, 1, 1)
        self.pushButtonDownloadDraftData = QtGui.QPushButton(self.verticalGroupBox_21)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonDownloadDraftData.sizePolicy().hasHeightForWidth())
        self.pushButtonDownloadDraftData.setSizePolicy(sizePolicy)
        self.pushButtonDownloadDraftData.setObjectName(_fromUtf8("pushButtonDownloadDraftData"))
        self.gridLayout.addWidget(self.pushButtonDownloadDraftData, 1, 14, 1, 1)
        self.label_5 = QtGui.QLabel(self.verticalGroupBox_21)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 0, 1, 1, 1)
        self.comboBoxLeagueType = QtGui.QComboBox(self.verticalGroupBox_21)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxLeagueType.sizePolicy().hasHeightForWidth())
        self.comboBoxLeagueType.setSizePolicy(sizePolicy)
        self.comboBoxLeagueType.setObjectName(_fromUtf8("comboBoxLeagueType"))
        self.comboBoxLeagueType.addItem(_fromUtf8(""))
        self.comboBoxLeagueType.addItem(_fromUtf8(""))
        self.comboBoxLeagueType.addItem(_fromUtf8(""))
        self.comboBoxLeagueType.addItem(_fromUtf8(""))
        self.comboBoxLeagueType.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBoxLeagueType, 1, 1, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 1, 10, 1, 1)
        self.label_6 = QtGui.QLabel(self.verticalGroupBox_21)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 0, 5, 1, 1)
        self.pushButtonResetDraftData = QtGui.QPushButton(self.verticalGroupBox_21)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonResetDraftData.sizePolicy().hasHeightForWidth())
        self.pushButtonResetDraftData.setSizePolicy(sizePolicy)
        self.pushButtonResetDraftData.setObjectName(_fromUtf8("pushButtonResetDraftData"))
        self.gridLayout.addWidget(self.pushButtonResetDraftData, 1, 9, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem6, 1, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.verticalGroupBox_21)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 0, 3, 1, 1)
        self.comboBoxNumberOfTeams = QtGui.QComboBox(self.verticalGroupBox_21)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxNumberOfTeams.sizePolicy().hasHeightForWidth())
        self.comboBoxNumberOfTeams.setSizePolicy(sizePolicy)
        self.comboBoxNumberOfTeams.setObjectName(_fromUtf8("comboBoxNumberOfTeams"))
        self.comboBoxNumberOfTeams.addItem(_fromUtf8(""))
        self.comboBoxNumberOfTeams.addItem(_fromUtf8(""))
        self.comboBoxNumberOfTeams.addItem(_fromUtf8(""))
        self.comboBoxNumberOfTeams.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBoxNumberOfTeams, 1, 3, 1, 1)
        self.pushButtonLoadFantasyData = QtGui.QPushButton(self.verticalGroupBox_21)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonLoadFantasyData.sizePolicy().hasHeightForWidth())
        self.pushButtonLoadFantasyData.setSizePolicy(sizePolicy)
        self.pushButtonLoadFantasyData.setObjectName(_fromUtf8("pushButtonLoadFantasyData"))
        self.gridLayout.addWidget(self.pushButtonLoadFantasyData, 1, 7, 1, 1)
        self.comboBoxDraftPick = QtGui.QComboBox(self.verticalGroupBox_21)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxDraftPick.sizePolicy().hasHeightForWidth())
        self.comboBoxDraftPick.setSizePolicy(sizePolicy)
        self.comboBoxDraftPick.setObjectName(_fromUtf8("comboBoxDraftPick"))
        self.comboBoxDraftPick.addItem(_fromUtf8(""))
        self.comboBoxDraftPick.addItem(_fromUtf8(""))
        self.comboBoxDraftPick.addItem(_fromUtf8(""))
        self.comboBoxDraftPick.addItem(_fromUtf8(""))
        self.comboBoxDraftPick.addItem(_fromUtf8(""))
        self.comboBoxDraftPick.addItem(_fromUtf8(""))
        self.comboBoxDraftPick.addItem(_fromUtf8(""))
        self.comboBoxDraftPick.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBoxDraftPick, 1, 5, 1, 1)
        self.lineEditMockDraftEnd = QtGui.QLineEdit(self.verticalGroupBox_21)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditMockDraftEnd.sizePolicy().hasHeightForWidth())
        self.lineEditMockDraftEnd.setSizePolicy(sizePolicy)
        self.lineEditMockDraftEnd.setObjectName(_fromUtf8("lineEditMockDraftEnd"))
        self.gridLayout.addWidget(self.lineEditMockDraftEnd, 1, 13, 1, 1)
        self.label_8 = QtGui.QLabel(self.verticalGroupBox_21)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 0, 11, 1, 1)
        self.label_9 = QtGui.QLabel(self.verticalGroupBox_21)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 0, 13, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem7, 1, 15, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout)
        self.tableWidgetDraftTable = QtGui.QTableWidget(self.verticalGroupBox_21)
        self.tableWidgetDraftTable.setMinimumSize(QtCore.QSize(951, 0))
        self.tableWidgetDraftTable.setObjectName(_fromUtf8("tableWidgetDraftTable"))
        self.tableWidgetDraftTable.setColumnCount(0)
        self.tableWidgetDraftTable.setRowCount(0)
        self.verticalLayout_6.addWidget(self.tableWidgetDraftTable)
        self.horizontalLayout_2.addWidget(self.verticalGroupBox_21)
        self.verticalGroupBox_22 = QtGui.QGroupBox(self.horizontalLayoutWidget_3)
        self.verticalGroupBox_22.setObjectName(_fromUtf8("verticalGroupBox_22"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.verticalGroupBox_22)
        self.verticalLayout_5.setMargin(11)
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setMargin(11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_3 = QtGui.QLabel(self.verticalGroupBox_22)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout.addWidget(self.label_3)
        self.label_7 = QtGui.QLabel(self.verticalGroupBox_22)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout.addWidget(self.label_7)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setMargin(11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pushButtonCalculateDraftOdds = QtGui.QPushButton(self.verticalGroupBox_22)
        self.pushButtonCalculateDraftOdds.setObjectName(_fromUtf8("pushButtonCalculateDraftOdds"))
        self.horizontalLayout.addWidget(self.pushButtonCalculateDraftOdds)
        self.comboBoxCalculateOddsRound = QtGui.QComboBox(self.verticalGroupBox_22)
        self.comboBoxCalculateOddsRound.setObjectName(_fromUtf8("comboBoxCalculateOddsRound"))
        self.comboBoxCalculateOddsRound.addItem(_fromUtf8(""))
        self.comboBoxCalculateOddsRound.addItem(_fromUtf8(""))
        self.comboBoxCalculateOddsRound.addItem(_fromUtf8(""))
        self.comboBoxCalculateOddsRound.addItem(_fromUtf8(""))
        self.comboBoxCalculateOddsRound.addItem(_fromUtf8(""))
        self.comboBoxCalculateOddsRound.addItem(_fromUtf8(""))
        self.comboBoxCalculateOddsRound.addItem(_fromUtf8(""))
        self.comboBoxCalculateOddsRound.addItem(_fromUtf8(""))
        self.comboBoxCalculateOddsRound.addItem(_fromUtf8(""))
        self.comboBoxCalculateOddsRound.addItem(_fromUtf8(""))
        self.comboBoxCalculateOddsRound.addItem(_fromUtf8(""))
        self.comboBoxCalculateOddsRound.addItem(_fromUtf8(""))
        self.comboBoxCalculateOddsRound.addItem(_fromUtf8(""))
        self.comboBoxCalculateOddsRound.addItem(_fromUtf8(""))
        self.comboBoxCalculateOddsRound.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.comboBoxCalculateOddsRound)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_5.addLayout(self.verticalLayout)
        self.textBrowserCalculateOdds = QtGui.QTextBrowser(self.verticalGroupBox_22)
        self.textBrowserCalculateOdds.setObjectName(_fromUtf8("textBrowserCalculateOdds"))
        self.verticalLayout_5.addWidget(self.textBrowserCalculateOdds)
        self.horizontalLayout_2.addWidget(self.verticalGroupBox_22)
        MainWindow.setCentralWidget(self.centralWidget)
        self.mainToolBar = QtGui.QToolBar(MainWindow)
        self.mainToolBar.setObjectName(_fromUtf8("mainToolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 2249, 17))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        MainWindow.setMenuBar(self.menuBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label.setText(_translate("MainWindow", "      Select Play to Draft or calculate draft odds", None))
        self.pushButtonDraftPlayer.setText(_translate("MainWindow", "Draft Selected Player", None))
        self.pushButtonUndoDraftedPlayer.setText(_translate("MainWindow", "Undo Drafted Player", None))
        self.label_2.setText(_translate("MainWindow", "                             Search Player", None))
        __sortingEnabled = self.listWidgetPlayerList.isSortingEnabled()
        self.listWidgetPlayerList.setSortingEnabled(False)
        item = self.listWidgetPlayerList.item(0)
        item.setText(_translate("MainWindow", "Load fantasy data to start", None))
        self.listWidgetPlayerList.setSortingEnabled(__sortingEnabled)
        self.pushButtonDownloadDraftData.setText(_translate("MainWindow", "Download Draft Data", None))
        self.label_5.setText(_translate("MainWindow", "     League Type", None))
        self.comboBoxLeagueType.setItemText(0, _translate("MainWindow", "Standard", None))
        self.comboBoxLeagueType.setItemText(1, _translate("MainWindow", "PPR", None))
        self.comboBoxLeagueType.setItemText(2, _translate("MainWindow", "2 QB", None))
        self.comboBoxLeagueType.setItemText(3, _translate("MainWindow", "Dynasty", None))
        self.comboBoxLeagueType.setItemText(4, _translate("MainWindow", "Dynasty Rookie", None))
        self.label_6.setText(_translate("MainWindow", "   Your Draft Position  ", None))
        self.pushButtonResetDraftData.setText(_translate("MainWindow", "Reset Data", None))
        self.label_4.setText(_translate("MainWindow", "  Number of Teams  ", None))
        self.comboBoxNumberOfTeams.setItemText(0, _translate("MainWindow", "8 Team", None))
        self.comboBoxNumberOfTeams.setItemText(1, _translate("MainWindow", "10 Team", None))
        self.comboBoxNumberOfTeams.setItemText(2, _translate("MainWindow", "12 Team", None))
        self.comboBoxNumberOfTeams.setItemText(3, _translate("MainWindow", "14 Team", None))
        self.pushButtonLoadFantasyData.setText(_translate("MainWindow", "Load Draft Data", None))
        self.comboBoxDraftPick.setItemText(0, _translate("MainWindow", "Pick 1", None))
        self.comboBoxDraftPick.setItemText(1, _translate("MainWindow", "Pick 2", None))
        self.comboBoxDraftPick.setItemText(2, _translate("MainWindow", "Pick 3", None))
        self.comboBoxDraftPick.setItemText(3, _translate("MainWindow", "Pick 4", None))
        self.comboBoxDraftPick.setItemText(4, _translate("MainWindow", "Pick 5", None))
        self.comboBoxDraftPick.setItemText(5, _translate("MainWindow", "Pick 6", None))
        self.comboBoxDraftPick.setItemText(6, _translate("MainWindow", "Pick 7", None))
        self.comboBoxDraftPick.setItemText(7, _translate("MainWindow", "Pick 8", None))
        self.label_8.setText(_translate("MainWindow", "Mock Draft Start", None))
        self.label_9.setText(_translate("MainWindow", "Mock Draft End", None))
        self.label_3.setText(_translate("MainWindow", "             Select player and round", None))
        self.label_7.setText(_translate("MainWindow", "                to find your odds", None))
        self.pushButtonCalculateDraftOdds.setText(_translate("MainWindow", "Calculate Draft Odds", None))
        self.comboBoxCalculateOddsRound.setItemText(0, _translate("MainWindow", "Round 1", None))
        self.comboBoxCalculateOddsRound.setItemText(1, _translate("MainWindow", "Round 2", None))
        self.comboBoxCalculateOddsRound.setItemText(2, _translate("MainWindow", "Round 3", None))
        self.comboBoxCalculateOddsRound.setItemText(3, _translate("MainWindow", "Round 4", None))
        self.comboBoxCalculateOddsRound.setItemText(4, _translate("MainWindow", "Round 5", None))
        self.comboBoxCalculateOddsRound.setItemText(5, _translate("MainWindow", "Round 6", None))
        self.comboBoxCalculateOddsRound.setItemText(6, _translate("MainWindow", "Round 7", None))
        self.comboBoxCalculateOddsRound.setItemText(7, _translate("MainWindow", "Round 8", None))
        self.comboBoxCalculateOddsRound.setItemText(8, _translate("MainWindow", "Round 9", None))
        self.comboBoxCalculateOddsRound.setItemText(9, _translate("MainWindow", "Round 10", None))
        self.comboBoxCalculateOddsRound.setItemText(10, _translate("MainWindow", "Round 11", None))
        self.comboBoxCalculateOddsRound.setItemText(11, _translate("MainWindow", "Round 12", None))
        self.comboBoxCalculateOddsRound.setItemText(12, _translate("MainWindow", "Round 13", None))
        self.comboBoxCalculateOddsRound.setItemText(13, _translate("MainWindow", "Round 14", None))
        self.comboBoxCalculateOddsRound.setItemText(14, _translate("MainWindow", "Round 15", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

